[project]
name = "codecheck"
version = "0.1.0"
description = ""
authors = [
    {name = "DigmaBalls",email = "DigmaBalls@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "fastapi[standard] (>=0.115.11,<0.116.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
